---
# tasks file for common

- name: Add epel yum repository
  yum: name=epel-release
  tags: yum

- name: Ensure common packages are installed
  yum: name={{ item }} state=present
  with_items:
    - ntp
    - wget
    - yum-plugin-priorities
    - python-lxml
  tags: yum

- name: Ensure ntpd service enabled and running
  service: name=ntpd enabled=yes state=started

- include: selinux.yml
  when: selinux_enabled | default(true)
