---
# tasks file for common

- name: Add epel yum repository
  yum: name=epel-release

- name: Ensure common packages are installed
  yum: name={{ item }} state=present
  with_items:
    - ntp
    - wget
    - policycoreutils-python
    - libsemanage-python
    - selinux-policy-targeted
    - yum-plugin-priorities
    - python-lxml

- name: Ensure SELINUX is enforcing
  lineinfile: dest=/etc/selinux/config state=present regexp="SELINUX=.*" line="SELINUX=enforcing"

- name: Restore default SELinux security contexts
  shell: restorecon -r -v /var/log && restorecon -r -v /etc/audit

- name: Ensure ntpd service enabled and running
  service: name=ntpd enabled=yes state=started

