---
- name: Download InfluxDB
  get_url:
    url: "https://dl.influxdata.com/influxdb/releases/influxdb-{{ influxdb_version }}.x86_64.rpm"
    dest: /tmp
    mode: 0755

- name: install influx rpm from a local file
  yum:
    name: "/tmp/influxdb-{{ influxdb_version }}.x86_64.rpm"
    state: present
