---
- name: Download InfluxDB
  when: not influxdb_retrieve_from_s3 | default(false)
  get_url:
    url: "https://dl.influxdata.com/influxdb/releases/influxdb-{{ influxdb_version }}.x86_64.rpm"
    dest: "{{ influxdb_dest }}"
    mode: 0755

- name: install influx rpm from a local file
  yum:
    name: "{{ influxdb_dest }}/{{ influxdb_filename }}"
    state: present
