---
# tasks file for mongo

- name: Add repository
  yum_repository:
    name: mongodb-org-{{ mongo_version }}
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongo_version }}/$basearch/
    gpgcheck: no

- name: install mongo
  yum: name=mongodb-org state=latest

- name: ensure conf directories exist
  file: path="{{ item }}" state=directory owner="{{ mongo_user }}" group="{{ mongo_user }}" mode=0755
  with_items:
    - "{{ mongo_db_dir }}"
  tags: [ dep ]

- name: copy system configs
  template: src="{{ item.src }}" dest="{{ item.dest }}" owner='root' group='root' mode='0644'
  with_items:
    - { src: '99-mongodb-nproc.conf.j2', dest: '/etc/security/limits.d/99-mongodb-nproc.conf' }
  tags: [ install, config ]

- name: copy mongo configs
  template: src="{{ item.src }}" dest="{{ item.dest }}" mode='0644'
  with_items:
    - { src: 'mongod.yaml.j2', dest: "{{ mongo_conf_file }}" }
  notify:
    - restart mongod
  tags: [ install, config ]

- name: Start mongo service (service mongod start)
  service: name=mongod state=started enabled=yes
