---
# tasks file for nifi_nars

- name: Ensure required directories exist
  file: path="{{ nifi_nars_base_dir }}" state=directory owner="{{ nifi_nars_user }}" group="{{ nifi_nars_group }}" mode=0755
  tags: [ install ]

# cannot use yum to install rpm because it will never upgrade (https://github.com/ansible/ansible-modules-core/issues/4529)
- name: Install nars via rpm
  command: "rpm --nosignature -U {{ nifi_nars_rpm }}"
  notify:
    - restart nifi
  tags: [ install ]

- name: Ensure symlink
  file: src="{{ nifi_nars_base_dir }}/{{ nifi_nars_dir }}" dest="{{ nifi_nars_symlink }}" state=link
  notify:
    - restart nifi
  tags: [ install ]

- name: Update nifi configs
  lineinfile:
    dest: "{{ nifi_conf_dir }}/nifi.properties"
    state: present
    regexp: "^nifi.nar.library.directory.{{ nifi_nars_id }}="
    line: "nifi.nar.library.directory.{{ nifi_nars_id }}={{ nifi_nars_symlink }}"
    insertafter: "^nifi.nar.library.directory="
  notify:
    - restart nifi
  tags: [ config ]

